export const proseClasses = [
  "prose",
  "dark:prose-invert",
  "font-serif",
  "prose-h1:font-sans prose-h1:mb-2 prose-h1:font-medium",
  "prose-h2:font-sans prose-h2:font-medium prose-h2:my-6",
  "prose-h3:font-sans prose-h3:font-medium prose-h3:my-4",
  "prose-h4:font-sans prose-h4:font-medium prose-h4:my-2",
  "prose-p:my-2",
  "prose-code:font-mono",
  "prose-pre:font-code",
  "prose-pre:rounded-[var(--radius-surface)]",
  "prose-blockquote:bg-secondary",
  "prose-blockquote:border-none",
  "prose-blockquote:rounded-[--radius-surface]",
  "prose-blockquote:py-4",
  "hover:prose-blockquote:translate-y-[-2px]",
  "prose-blockquote:not-italic",
  "prose-blockquote:transition-all",
  "prose-img:w-full",
].join(" ");
